### ISSUE TITLE
Add to PyPi package manager

### ISSUE THREAD

**Issue by Tungsteno74** [JeffHoogland/pyxhook#16]
#Hello,
i like your package, but i think that a better way to use it is to add it on PyPi.
Can you do that? 
If you like to do this but you will have some troubles, I would be happy to help you. I own a couple of modules on PyPi.

Thanks

**Comment by JeffHoogland** [comment]
Feel free to make a pull request that will allow. I don't plan to spend time on it personally.

**Comment by Tungsteno74** [comment]
Thanks for your reply. I checked the license and i prefer to use one more freeware. For now i no need this project anymore. 
Thanks for your time!
