### ISSUE TITLE
Conflicting notices of Copyright.

### ISSUE THREAD

**Issue by LandonPowell** [JeffHoogland/pyxhook#6]
Your license.txt conflicts with the pyxhook.py's built in notice of license, and you've claimed copyright with all rights reserved over someone else's unmodified GPLv2 software. The GPL prohibits sublicensing.

**Comment by JeffHoogland** [comment]
That license file only applies to files in the repository that do not have an otherwise state license contained within them.

**Comment by LandonPowell** [comment]
Nothing in your repo is valid for copyright other than pyhook. `example.py` falls under commonly known information, and your readme does even more so.
