### ISSUE TITLE
120% CPU usage after a few minutes

### ISSUE THREAD

**Issue by NAMB-develop** [JeffHoogland/pyxhook#8]
`def pr(e):
    print(e)

import pyxhook as H
manager=H.HookManager()
manager.KeyDown = pr
#manager.HookKeyboard()
manager.start()`

When using the above code and using the latest pyxhook (Python 2.7), the process starts to consume 100% CPU after several minutes (current sample: 20seconds, 1minute30seconds,4minutes,20minutes). Printing events also stops.
The same thing happens when I run pyxhook. There seems to be a part of the code that fails silently (perhaps it is silent because of threading?). 

`manager.cancel()` does not cancel the thread, corroborating the idea that something has failed somewhere. Could you have a look at this? Ctrl+C also does not exit the code. Ctrl+Z makes the process zombie.

I saw that your implementation shares parts of code with the recorder_demo.py from Xlib. When I run the recorder_demo.py, I do not get the large CPU usage. 

It seems to consistently fail when I press [Return] with an active firefox window. Maybe this helps?

**Comment by JeffHoogland** [comment]
As mentioned in the read me I am not the original author of this code.
Wouldn't know the first place where to start debugging performance issues.

**Comment by NAMB-develop** [comment]
Dang. Okay.
Well, do you fancy a pull request when I figure it out? Or is that also out of the scope of this repository?

**Comment by JeffHoogland** [comment]
Improvements that do not hamper functionality are welcome.

**Comment by NAMB-develop** [comment]
I figured the cause of this error is not in pyxhook, but in xlib. You can close this issue.
